--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TwistedAsylumMC/BedrockServerQuery
build-by-default: true
branches:
- master
projects:
  BedrockServerQuery:
    path: ""
    model: virion
    type: library
...
